name: Build and Deploy Angular to Azure Storage

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration=${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

      - name: Deploy to Azure Storage
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob delete-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --auth-mode key --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} --source '$web'
            az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --auth-mode key --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} --source ./dist/open-test-vaire/browser --destination '$web'
        env:
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
